version: '3.8'

services:
  postgres:
    container_name: postgres-recipedia
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: recipedia
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - recipedia-demo
  mail-dev:
    container_name: mail-dev-recipedia
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
networks:
  recipedia-demo:
    driver: bridge

volumes:
  postgres:
    driver: local