package com.recipedia.domain;

public enum RecipeTag {
    VEGAN, SALAD, SANDWICH, SOUP, SPICY, DESSERT, PASTA,
    BBQ, SEAFOOD, HEALTHY, EASY, MEDITERRANEAN, APPETIZER,
    SNACK, BAKED, GRILLED, QUICK, KETO, HOLIDAY, PALEO
}
