spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recipedia
    username: user
    password: root
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: localhost
    port: 1025
    username: rzn
    password: rzn
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: recipedia
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 172800000 #48 hours
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    uploads:
      default-profile-picture: ./uploads/users/defaultPfp/dpic.jpeg
      no-image: ./uploads/recipes/no-img.jpeg
      image-output-path: ./uploads

server:
  servlet:
    context-path: /api/v1/